---
title: "final_project"
author: "Caroline Behrens"
date: "4/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggthemes)
library(rstanarm)
library(ggdist)
library(gt)
library(janitor)
library(broom.mixed)
library(gtsummary)
library(tidybayes)
library(ggplot2)
library(viridis)
library(hrbrthemes)
library(dplyr)
library(forcats)
```

```{r}
library(readr)
crime_data <-  read_csv("prison/raw_data/crime_and_incarceration_by_state.csv")
View(crime_and_incarceration_by_state)
```


```{r}
mortality_data <- msfp0116stt12 <- read_csv("Prison/raw_data/msfp0116stt12.csv")
View(msfp0116stt12)
```

```{r}
total_mortality <- mortality_data %>%
  rename(jurisdiction = `State/Federal`) %>%
 filter(!(jurisdiction %in% c("Federal", "State"))) %>%
  select(-"2001 caveat", -"2006 caveat", -"2007 caveat", -"2008 caveat", -"2009 caveat",
         -"2010 caveat", -"2011 caveat", -"2012 caveat", -"2013 caveat", -"2014 caveat",
         -"2015 caveat", -"2016 caveat")
```


```{r}
total_mortality %>%
  pivot_longer(names_to = "year",
               values_to = "Mortality_Count",
               cols =  `2001` : `2016`)

```


```{r}
 crime_and_incarceration_by_state <- crime_data %>%
  mutate(jurisdiction = str_to_title(jurisdiction)) %>%
  filter(jurisdiction != "Federal")

```

```{r}
state_crime <- crime_and_incarceration_by_state %>%
  sample_n(1000, replace = TRUE) %>%
  mutate(name = str_to_sentence(jurisdiction)) %>%
inner_join(total_mortality, by = "jurisdiction") %>%
  select(name, year, violent_crime_total,agg_assault, 
murder_manslaughter, robbery, property_crime_total,
larceny, vehicle_theft) %>%
  pivot_longer(names_to = "type",
               values_to = "total",
               cols = c(property_crime_total, violent_crime_total))

state_crime
```




```{r}
clean_crime <- crime_and_incarceration_by_state %>%
 mutate(south = ifelse(jurisdiction %in% c("ALABAMA", "FLORIDA", "GEORGIA", "KENTUCKY",
                                            "LOUISIANA", "MARYLAND", "MISSISSIPPI",
                                            "NORTH CAROLINA", "OKLAHOMA", "SOUTH CAROLINA",
                                            "TENNESSEE", "TEXAS", "VIRGINIA", "WEST VIRGINIA"),
                        TRUE, FALSE)) %>%
  mutate(population_in_thousands = state_population/1000) %>%
  mutate(prisoner_count_in_thousands = prisoner_count/1000) %>%
  mutate(violent_crime_in_thousands = violent_crime_total/1000) %>%
  drop_na(population_in_thousands) %>%
  drop_na(prisoner_count_in_thousands) %>%
  drop_na(violent_crime_in_thousands)
```

$$ prisoner\_count\_in\_thousands_i = \beta_0 + \beta_1 population\_bins_i + \beta_2 south_i + \beta_3 violent\_crime\_in\_thousands_i + \beta_4 south*violent\_crime\_in\_thousands_i + \epsilon_i$$ 

```{r}
crime_w_bins <- clean_crime %>%
 mutate(south = ifelse(jurisdiction %in% c("Alabama", "Florida", "Georgia", "Kentucky",
                                            "Louisiana", "Maryland", "Mississippi",
                                            "North Carolina", "Oklahoma", "South Carolina",
                                            "Tennessee", "Texas", "Virginia", "West Virginia"),
                        TRUE, FALSE)) %>%
  mutate(population_in_thousands = state_population/1000) %>%
  mutate(prisoner_count_in_thousands = prisoner_count/1000) %>%
  mutate(violent_crime_in_thousands = violent_crime_total/1000) %>%
  drop_na(population_in_thousands) %>%
  drop_na(prisoner_count_in_thousands) %>%
  drop_na(violent_crime_in_thousands) %>%
  mutate(population_bins = case_when(population_in_thousands < 8000 ~ 1,
                                     population_in_thousands >= 8000 & population_in_thousands <16000 ~ 2,
                                     population_in_thousands >= 16000 & population_in_thousands <24000 ~ 3,
                                     population_in_thousands >= 24000 & population_in_thousands < 32000 ~ 4,
                                     population_in_thousands >= 32000 & population_in_thousands < 40000 ~ 5)) %>%
  mutate(violent_crime_bins = case_when(violent_crime_in_thousands < 43 ~ 1,
                                        violent_crime_in_thousands  >= 43 & violent_crime_in_thousands < 86 ~2,
                                        violent_crime_in_thousands >= 86 & violent_crime_in_thousands < 129 ~ 3,
                                        violent_crime_in_thousands >= 129 & violent_crime_in_thousands < 172 ~ 4,
                                        violent_crime_in_thousands >= 172 & violent_crime_in_thousands < 215 ~ 5))
```



```{r}
fit_1 <- stan_glm(prisoner_count_in_thousands ~ population_bins + south + violent_crime_bins + south*violent_crime_bins,
                  data = crime_w_bins, 
                  seed = 17,
                  refresh = 0)
print(fit_1, digits = 4)


  saveRDS(fit_1, file = "prisoner_fit2.RDS")
```
*section 6.3*
*chapter 9* 

```{r}
model_prisoner_count <-tbl_regression(fit_1,
               intercept = TRUE,
               estimate_fun = function(x) style_sigfig(x, digits = 3)) %>%
  as_gt() %>%
    tab_header(title = "Prisoner Count Varies Greatly by Population") %>%
    tab_source_note(md("Source: Data.world "))

model_prisoner_count

```




```{r}
population_bins <- unique(crime_w_bins$population_bins)
south <- unique(crime_w_bins$south)
violent_crime_bins <- unique(crime_w_bins$violent_crime_bins)

newobs_1 <- expand_grid(population_bins, south, violent_crime_bins)
```

```{r, message=FALSE}
real_p <-add_fitted_draws(newobs_1, fit_1)

 pe <- posterior_epred(fit_1, newdata = newobs_1) %>% 
  as_tibble() %>%
  ggplot(aes(x = `2`)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),
                   bins = 100)  +
    labs(title = "Posterior for Priosner Count",
         subtitle = "Southern State Has around 90,000 Prisoners",
         x = "Prisoner Count (Thousands)",
         y = "Probability") +
    scale_x_continuous(labels = scales::number_format()) +
    scale_y_continuous(labels = scales::percent_format()) +
    theme_classic()
 
 pe

```
```{r}
real_p <-add_fitted_draws(newobs_1, fit_1) 

real_p %>%
  ggplot(aes(x = population_bins, y = .value, colour = violent_crime_bins)) +
  geom_jitter(alpha = .5) + 
  geom_smooth(formula = y ~ x,
              method = "lm") +
  facet_wrap(~south) +
  labs(title = "Prisoner Count", subtitle = "Geographical location has great effect",
       x = "Population Bins", y = "Prisoner Count  (Thousands)")
```







```{r}
mortality_numbers <- total_mortality %>%
  pivot_longer(names_to = "Year",
               values_to = "Mortality_Number",
               cols = c(`2001`, `2006`, `2007`, `2008`, `2009`,`2010`, `2011`, `2012`,
               `2013`, `2014`,`2015`,`2016`)) %>%
  mutate(south = ifelse(jurisdiction %in% c("Alabama", "Florida", "Georgia", "Kentucky",
                                            "Louisiana", "Maryland", "Mississippi",
                                            "North Carolina", "Oklahoma", "South Carolina",
                                            "Tennesse", "Texas", "Virginia", "West Virginia"),
                        TRUE, FALSE))
```


```{r}
#mortality_numbers %>%
  #ggplot(aes(x = "mortality_number",y = , fill = south)) + 
 # geom_point(alpha = 0.05) + 
 # geom_smooth()


mortality_plot <- ggplot(data = mortality_numbers, 
       mapping = aes(x = Year, 
                     y = Mortality_Number, 
                     color = south)) +
  geom_point(alpha = 0.5) + 
  labs(title = "Mortality Numbers in Prisons",
  subtitle = "Typically Higher Mortality in Southern State Prisons",
  x = "Year", y = "Mortality Number")
  
mortality_plot
```


```{r}
  qplot(Year, Mortality_Number, data = mortality_numbers, 
      geom= "violin", fill = south, outlier.color = "transparent")  

```

```{r}
# mortality_numbers %>%
#   ggplot(aes(fill=south, y=Mortality_Number, x=Year)) + 
#     geom_violin(position="dodge", alpha=0.5, outlier.colour="transparent")
```



```{r}
crime_per_state <- crime_w_bins %>%
  filter(jurisdiction == "Alabama") %>%
ggplot(aes(y = robbery, x = year)) + 
  geom_line()
crime_per_state
```

